### ISSUE TITLE
[docs] Licentie checks van CPP libs uitvoeren in extra/common

### ISSUE THREAD

**Issue by rmoesbergen** [leaphy-robotics/leaphy-extensions#1]
We gebruiken veel externe libs, soms gestripped van comments/copyrights en gekopieerd. Dat is vaak niet toegestaan volgens de licentie van de libs. Dit nakijken en waar nodig corrigeren en comments/authors/copyrights laten staan.

**Comment by rmoesbergen** [comment]
src/Adafruit_TCS34725.cpp: ✅  (BSD, comments intact)
src/AirQuality.h: ✅ (MIT, comments intact)
src/LSM303AGR.cpp: ✅ (Eigen file met Adafruit library dep)
src/Leaphy_Extra.cpp: ✅ (Eigen file, geen deps)
src/Leaphyoriginal1.cpp: ✅ (Eigen file, geen deps)
src/LightSensor.cpp: ✅ (Eigen file, geen deps, kan naar webbased)
src/Magnet.cpp: ✅ (Eigen file, geen deps)
src/OLED_Display.cpp: ✅ (Eigen file met Adafruit dep, kan naar webbased)
src/RedMP3.cpp: ✅ (GLPL, comments intact)
src/TimeofFlight.cpp: ✅ (Eigen file met Adafruit dep, kan naar webbased)
src/ledstrip.cpp: ✅ (Eigen file met Adafruit dep)

Er zijn dus geen license issues (meer), wel kunnen er nog een bergje files uit de repo naar webbased verplaatst (C++ code in een generator stoppen ipv. in de eigen library).

**Comment by koen1711** [comment]
I asumme this is done? Right @rmoesbergen?
